name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check security vulnerabilities
      run: |
        pip install safety
        safety check
    
    - name: Create dummy credentials for testing
      run: |
        echo '{"type": "service_account"}' > google-credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=./google-credentials.json" > .env
        echo "OPENAI_API_KEY=dummy-key" >> .env
    
    - name: Run static type checking
      run: |
        pip install mypy
        mypy --ignore-missing-imports . 